services:
  - type: web
    name: asl-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    plan: free
    region: oregon
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - render.yaml
    preBuildCommand: ./setup.sh
